import { readFileSync } from "node:fs";
import { join } from "node:path";
import { commands, creationCommands, pipelineCommands } from "./commands.ts";
import {
  type ActiveSchemaBaseline,
  lintCommands,
  lintActionSurface,
  lintSchema,
  type Schema,
} from "./define.ts";
import {
  competitor,
  market_event,
  instrument,
  quote,
  venue,
  result,
  participates_in,
  offered_on,
  quotes,
  lists,
  settles,
  start_event,
  settle_event,
  void_event,
  ingest_market_batch,
} from "./ontology/market.ts";
import {
  mission,
  policy,
  environment,
  hypothesis,
  strategy,
  ticket,
  dataset,
  run,
  artifact,
  evaluation,
  tests,
  has_leg,
  uses,
  executes_in,
  produces,
  derived_from,
  evaluated_by,
  gates,
  create_hypothesis,
  register_dataset_version,
  create_run,
  create_mission,
  create_ticket,
  observe_ticket,
  start_run,
  cancel_run,
  complete_run,
  fail_run,
  grade_ticket,
  publish_artifact,
  record_evaluation,
  resolve_hypothesis,
} from "./ontology/research.ts";
import {
  workspace,
  agent_definition,
  agent_session,
  task,
  tool,
  execution_environment,
  connection,
  assigned_to,
  delegates_to,
  spawned_from,
  register_agent_definition,
  create_agent_session,
  start_agent_session,
  block_agent_session,
  unblock_agent_session,
  cancel_agent_session,
  fail_agent_session,
  close_agent_session,
} from "./ontology/agent.ts";
import { transitions } from "./transitions.ts";

export * from "./ontology/market.ts";
export * from "./ontology/research.ts";
export * from "./ontology/agent.ts";

/** Full schema v0.2 in declaration order — generators must preserve this order. */
export const schema: Schema = {
  objects: [
    competitor,
    market_event,
    instrument,
    quote,
    venue,
    result,
    mission,
    hypothesis,
    policy,
    environment,
    strategy,
    ticket,
    dataset,
    run,
    artifact,
    evaluation,
    workspace,
    agent_definition,
    agent_session,
    task,
    tool,
    execution_environment,
    connection,
  ],
  links: [
    participates_in,
    offered_on,
    quotes,
    lists,
    settles,
    tests,
    has_leg,
    uses,
    executes_in,
    produces,
    derived_from,
    evaluated_by,
    gates,
    assigned_to,
    delegates_to,
    spawned_from,
  ],
  actions: [
    create_hypothesis,
    register_dataset_version,
    create_run,
    create_mission,
    create_ticket,
    observe_ticket,
    start_run,
    cancel_run,
    complete_run,
    fail_run,
    grade_ticket,
    start_event,
    settle_event,
    void_event,
    ingest_market_batch,
    register_agent_definition,
    create_agent_session,
    start_agent_session,
    block_agent_session,
    unblock_agent_session,
    cancel_agent_session,
    fail_agent_session,
    close_agent_session,
    publish_artifact,
    record_evaluation,
    resolve_hypothesis,
  ],
};

const schemaBaselinePath = join(import.meta.dir, "..", "schema-baseline.json");
const baselineJson = readFileSync(schemaBaselinePath, "utf8");
const activeSchemaBaseline = JSON.parse(baselineJson) as ActiveSchemaBaseline;
const skipActiveFreeze = process.env.QF_SCHEMA_SKIP_ACTIVE_FREEZE === "1";

lintSchema(schema, transitions, activeSchemaBaseline, { skipActiveFreeze });
lintCommands(schema, transitions, commands, creationCommands, pipelineCommands);
lintActionSurface(schema, commands, creationCommands, pipelineCommands);
