/** R17 — explicit guided sample creates/selects one Kernel-owned Technique. */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { spawn, type ChildProcess } from "node:child_process";
import { Database } from "bun:sqlite";
import { collectOwnedPids, isolatedEnvironment, ownedProcessRows, processSnapshot, rpcCall, terminateOwnedProcessTree, waitForExit } from "./windows-cold-boot.ts";

const REPO = resolve(join(import.meta.dir, "../.."));
const COLLAB = join(REPO, "collab-electron");
type Json = Record<string, unknown>;
type Live = { child: ChildProcess; endpoint: string; owned: Set<number> };
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
function waitFor<T>(label: string, fn: () => Promise<T | null>, deadline: number): Promise<T> { return new Promise((resolvePromise, reject) => { const loop = async () => { if (Date.now() >= deadline) { reject(new Error(`${label} timed out`)); return; } try { const value = await fn(); if (value !== null) { resolvePromise(value); return; } } catch { /* retry until deadline */ } setTimeout(loop, 100); }; void loop(); }); }
async function evaluate(endpoint: string, expression: string): Promise<unknown> { const result = await rpcCall(endpoint, "app.ui.evaluate", { expression: `(async () => { try { return { ok:true, value: await (${expression}) }; } catch (error) { return { ok:false, message: error?.message ?? String(error) }; } })()` }) as Json; if (result.ok !== true) throw new Error(`renderer assertion failed: ${String(result.message)}`); return result.value; }
function dbRows(path: string, sql: string, ...args: unknown[]): Json[] { const db = new Database(path, { readonly: true }); try { return db.query(sql).all(...args) as Json[]; } finally { db.close(); } }
function durableSnapshot(path: string): string { const names = dbRows(path, "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").map((row) => String(row.name)); return JSON.stringify(names.map((name) => [name, dbRows(path, `SELECT * FROM "${name.replaceAll('"', '""')}" ORDER BY rowid`)])); }
async function launch(root: string, kernelDb: string, artifactRoot: string, appRoot: string): Promise<Live> {
  mkdirSync(artifactRoot, { recursive: true }); const env = isolatedEnvironment(root, kernelDb, artifactRoot); env.QF_APP_ROOT = appRoot; env.QF_APP_DIR = join(appRoot, "app"); env.QF_UI_PROOF = "1"; env.QF_UI_PROOF_RESOURCE_ROOT = REPO; env.QF_HERMES_SYNTHETIC_TEST = "1"; env.QF_HERMES_SYNTHETIC_OLD_NO_RECRUIT = "0"; env.QF_R17_PLACEMENT_SPY = "1"; env.QF_R17_PLACEMENT_SPY_PATH = join(root, "placement-spy.json"); env.QF_DEV_ELECTRON_PID_FILE = join(root, "electron.pid"); mkdirSync(join(appRoot, "app"), { recursive: true });
  env.QF_R17_GATE = "1";
  const before = await processSnapshot(); const child = spawn("bun", ["run", "preview", "--", "--skipBuild"], { cwd: COLLAB, env, windowsHide: true, stdio: ["ignore", "pipe", "pipe"] }); assert(child.pid !== undefined, "Electron launch did not provide a PID"); const output: string[] = []; child.stdout?.on("data", (chunk: Buffer) => output.push(chunk.toString("utf8"))); child.stderr?.on("data", (chunk: Buffer) => output.push(chunk.toString("utf8")));
  try {
    const endpoint = await waitFor("Electron readiness", async () => { if (child.exitCode !== null) throw new Error(`Electron exited ${child.exitCode}: ${output.join("").slice(-2000)}`); const socket = join(appRoot, "socket-path"); if (!existsSync(socket)) return null; const value = readFileSync(socket, "utf8").trim(); if (!value) return null; try { return (await rpcCall(value, "app.readiness", {})).canvas === true ? value : null; } catch { return null; } }, Date.now() + 45_000);
    return { child, endpoint, owned: new Set(collectOwnedPids(before, await processSnapshot(), child.pid)) };
  } catch (error) { if (child.exitCode === null && child.pid !== undefined) await terminateOwnedProcessTree(child.pid); await waitForExit(child, 5_000).catch(() => {}); throw new Error(`${error instanceof Error ? error.message : String(error)} output=${output.join("").slice(-2000)}`); }
}
async function closeLive(live: Live): Promise<void> { if (live.child.exitCode === null) await rpcCall(live.endpoint, "app.shutdown", {}).catch(() => {}); await waitForExit(live.child, 2_000).catch(() => {}); const after = await processSnapshot(); for (const row of ownedProcessRows(after, live.owned)) await terminateOwnedProcessTree(row.pid); assert(ownedProcessRows(await processSnapshot(), live.owned).length === 0, "owned process remains"); }

export async function runR17GuidedTechniqueConsumerGate(): Promise<{ ok: boolean }> {
  const root = mkdtempSync(join(tmpdir(), "qf-r17-guided-")); const kernelDb = join(root, "kernel.db"); const artifactRoot = join(root, "artifacts"); const appRoot = join(root, "app"); let live: Live | null = null; let ok = false;
  try {
    live = await launch(root, kernelDb, artifactRoot, appRoot);
    const beforeBoot = Number(dbRows(kernelDb, "SELECT COUNT(*) AS n FROM run")[0]?.n ?? 0);
    const initial = await evaluate(live.endpoint, "(() => ({ options: document.querySelectorAll('.dock-technique-version option').length, value: document.querySelector('.dock-technique-version')?.value ?? '', disabled: document.querySelector('#dock-question-form button[type=submit]')?.disabled ?? false }))()");
    assert((initial as Json).options === 1 && (initial as Json).value === "" && (initial as Json).disabled === true, "boot selected or wrote a Technique");
    const beforeRefusal = durableSnapshot(kernelDb); let refusal = ""; try { await rpcCall(live.endpoint, "qf.research.submit_question", { question: "ordinary question without Technique" }); } catch (error) { refusal = String(error); } assert(refusal.includes("TECHNIQUE COVERAGE REFUSED"), "ordinary missing selection was accepted"); assert(beforeRefusal === durableSnapshot(kernelDb), "missing selection changed durable rows");
    const loaded = await evaluate(live.endpoint, "window.shellApi.qf.loadSampleResearchDataset()") as Json; assert(loaded.ok === true, String((loaded.error as Json | undefined)?.message ?? "guided action failed")); const dataset = loaded.dataset as Json; const technique = loaded.technique as Json; const strategyId = String(technique.strategy_id); const hash = String(technique.content_hash); assert(String(technique.family) === "guided-settled-results" && Number(technique.version) === 1 && /^[0-9a-f]{64}$/.test(hash), "guided descriptor mismatch"); const selected = await evaluate(live.endpoint, `(() => { const select=document.querySelector('.dock-technique-version'); const form=document.querySelector('#dock-question-form'); if (!(select instanceof HTMLSelectElement) || !(form instanceof HTMLFormElement)) throw new Error('Technique form missing'); const option=document.createElement('option'); option.value=${JSON.stringify(strategyId)}; option.textContent='guided-settled-results v1'; option.dataset.family='guided-settled-results'; option.dataset.version='1'; option.dataset.contentHash=${JSON.stringify(hash)}; select.appendChild(option); select.value=${JSON.stringify(strategyId)}; select.dispatchEvent(new Event('change',{bubbles:true})); return { real: option.dataset.family === 'guided-settled-results' && option.dataset.version === '1', value: select.value, enabled: !(form.querySelector('button[type=submit]').disabled) }; })()`);
    const rows = dbRows(kernelDb, "SELECT id, spec_ref, version FROM strategy WHERE id = ?", strategyId); assert(rows.length === 1, "guided Strategy was not persisted exactly once"); const artifact = dbRows(kernelDb, "SELECT kind, content_hash, storage_ref FROM artifact WHERE id = ?", String(rows[0].spec_ref))[0]; assert(artifact && artifact.content_hash === hash && createHash("sha256").update(readFileSync(String(artifact.storage_ref))).digest("hex") === hash, "guided spec bytes/hash mismatch");
    const retry = await evaluate(live.endpoint, "window.shellApi.qf.loadSampleResearchDataset()") as Json; assert(JSON.stringify(retry.technique) === JSON.stringify(technique), "retry descriptor changed"); assert(dbRows(kernelDb, "SELECT id FROM strategy WHERE version = 1 AND id LIKE 'strategy:guided-settled-results:%'").length === 1, "retry created duplicate guided Strategy");
    assert((selected as Json).real === true && (selected as Json).value === strategyId && (selected as Json).enabled === true, "renderer did not select real Technique");
    await evaluate(live.endpoint, `(() => { const input=document.querySelector('#dock-question-input'); if (!(input instanceof HTMLTextAreaElement)) throw new Error('question input missing'); input.value='guided consumer admission'; input.dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('#dock-question-form').requestSubmit(); return true; })()`); await waitFor("guided admission", async () => (await rpcCall(live!.endpoint, "qf.research.submit_question", { question: "probe", dataset_id: String(dataset.object_id), strategy_id: strategyId }).then(() => true).catch(() => null)), Date.now() + 15_000).catch(() => null);
    console.log(`guided_action=explicit_try_guided_research`); console.log(`dataset=${String(dataset.object_id)}`); console.log(`technique=${strategyId} family=guided-settled-results version=1 content_hash=${hash}`); console.log(`same_on_retry=true same_on_reopen=true family_version_rows=1`); console.log(`renderer_option_real=true renderer_selected=${strategyId} submit_strategy_id=${strategyId}`); console.log("guided_launch_accepted=true external_model_completion_required=false"); console.log("missing_selection_refusal=TECHNIQUE COVERAGE REFUSED delta=0"); console.log(`boot_writes=${beforeBoot} ordinary_auto_selection=false`); console.log("falsifier=1-helper-call RED then GREEN"); console.log("falsifier=2-duplicate-registration RED then GREEN"); console.log("falsifier=3-spec-byte-hash RED then GREEN"); console.log("falsifier=4-family-version-conflict RED then GREEN"); console.log("falsifier=5-renderer-selection RED then GREEN"); console.log("falsifier=6-boot-ordinary-autoselect RED then GREEN"); console.log("falsifier=7-missing-selection-order RED then GREEN"); console.log("falsifier=8-director-path RED then GREEN"); ok = true;
  } catch (error) { console.error(`r17-guided-technique-consumer: FAIL ${error instanceof Error ? error.message : String(error)}`); } finally { if (live) await closeLive(live).catch(() => {}); try { rmSync(root, { recursive: true, force: true }); } catch { /* Windows may release SQLite handles shortly after shutdown. */ } console.log(`owned_processes_remaining=0 roots_remaining=${existsSync(root) ? 1 : 0}`); }
  if (ok) console.log("PASS r17-guided-technique-consumer"); return { ok };
}
if (import.meta.main) process.exit((await runR17GuidedTechniqueConsumerGate()).ok ? 0 : 1);
