// qf-atlas / markdown.mjs — the agent-facing brief. Generated, never hand-written.
// This is the file you point an architect at instead of explaining QuantFlow.

export function renderMarkdown(m) {
  const L = (id) => m.layers.find((l) => l.id === id);
  const nodesOf = (id) => m.nodes.filter((n) => n.layer === id).sort((a, b) => b.kb - a.kb);
  const prod = m.violations.filter((v) => v.scope === "product");
  const qa = m.violations.filter((v) => v.scope === "qa");
  const byKind = (k) => m.strip.filter((s) => s.kind === k);

  const out = [];
  const p = (s = "") => out.push(s);

  p(`# QuantFlow — how the program is wired`);
  p();
  p(`> Generated by \`qf-atlas/generate.mjs\` from ${m.meta.branch} @ ${m.meta.commit} on ${m.meta.generatedAt}.`);
  p(`> **A projection of the code, not Kernel truth and not the running app.** The Kernel still owns`);
  p(`> Missions, Tasks, Runs and Evaluations. This file owns one claim: this is how the program is`);
  p(`> wired right now. Do not hand-edit it — run the generator.`);
  p();
  p(`## Read this first`);
  p();
  p(`QuantFlow is an Electron research console. Work flows across three hops:`);
  p();
  p("```");
  p("renderer (canvas, tiles, dock)   →   preload (contextBridge)   →   main (handlers)   →   Kernel");
  p("     a window surface                a named IPC channel          ipcMain.handle       execute()");
  p("```");
  p();
  p(`A **wire** is one IPC channel traced across those hops. A wire is only as good as its weakest`);
  p(`hop, and the atlas classifies every one of them:`);
  p();
  p(`| Status | Meaning | Count |`);
  p(`|---|---|---:|`);
  p(`| \`live\` | renderer calls it, preload forwards it, main handles it | ${m.stats.live} |`);
  p(`| \`unused\` | preload exposes it and main handles it, but no renderer file calls it | ${m.stats.unused} |`);
  p(`| \`unreached\` | main registers a handler that nothing forwards to | ${m.stats.unreached} |`);
  p(`| \`dead\` | preload calls a channel no handler registers — **fails at runtime** | ${m.stats.dead} |`);
  p();
  p(`**${m.stats.channels} channels total across ${m.stats.nodes} subsystems in ${m.meta.filesScanned} files.**`);
  p();

  p(`## The floors`);
  p();
  for (const layer of m.layers) {
    const ns = nodesOf(layer.id);
    const kb = ns.reduce((s, n) => s + n.kb, 0).toFixed(0);
    p(`### LVL ${layer.id} · ${layer.name}`);
    p();
    p(`${ns.length} subsystems, ${kb} KB.`);
    p();
    const top = ns.slice(0, 8);
    p(`| Subsystem | Size | Files | Notes |`);
    p(`|---|---:|---:|---|`);
    for (const n of top) {
      const notes = [];
      if (n.executes) notes.push(`${n.executes} execute() calls`);
      if (n.dml) notes.push(`${n.dml} SQL`);
      if (n.spawns) notes.push(`${n.spawns} spawn`);
      if (n.writes) notes.push(`${n.writes} disk write`);
      if (n.strip.length) notes.push(`**${n.strip.length} to strip**`);
      p(`| \`${n.name}\` | ${n.kb} KB | ${n.files.length} | ${notes.join(" · ") || "—"} |`);
    }
    if (ns.length > top.length) p(`| …${ns.length - top.length} more | | | see \`atlas.json\` |`);
    p();
  }

  p(`## What should be removed (${m.strip.length})`);
  p();
  p(`This is the first job of the atlas: everything below is reachable-by-nobody or calls-nothing.`);
  p();
  for (const [kind, title, blurb] of [
    ["dead-wire", "Dead wires — these fail at runtime", "preload calls a channel that no handler registers"],
    ["unreached-ipc", "Unreached handlers", "registered in main, nothing forwards to them"],
    ["unused-bridge", "Unused bridge methods", "exposed to the renderer and wired to a live handler, but never called"],
  ]) {
    const items = byKind(kind);
    if (!items.length) continue;
    p(`### ${title} (${items.length})`);
    p();
    p(`_${blurb}_`);
    p();
    for (const s of items) p(`- \`${s.what}\` — ${s.where}`);
    p();
  }

  p(`## Write-door violations (${prod.length} product, ${qa.length} qa)`);
  p();
  p(`\`START_HERE §1\`: the Kernel owns truth. The declared write door is \`execute.ts\`, \`create.ts\`,`);
  p(`\`insert.ts\`, \`events.ts\`, \`db.ts\`, \`upgrade.ts\`, plus generated schema SQL. Any other file`);
  p(`holding SQL appears here automatically.`);
  p();
  p(`| File | Statements | Scope |`);
  p(`|---|---:|---|`);
  for (const v of m.violations) p(`| \`${v.where}\` | ${v.lines.length >= 6 ? "6+" : v.lines.length} | ${v.scope} |`);
  p();

  p(`## Staying true`);
  p();
  p("```bash");
  p("bun qf-atlas/generate.mjs           # rewrite the map from source");
  p("bun qf-atlas/generate.mjs --check   # fail if the committed map is stale");
  p("```");
  p();
  p(`\`--check\` regenerates in memory and compares. If the code moved and the map did not, it exits 1.`);
  p(`That is the whole contract: **the map cannot lie for longer than one commit.**`);
  p();
  return out.join("\n");
}
