import { transitions } from "../transitions.ts";

/**
 * Pure generator: transition tables in → conformance test file string out.
 * Emits accept tests for every legal edge and reject tests for every illegal target.
 */
export function generateConformance(): string {
  const lines: string[] = [];
  lines.push("// GENERATED by qf-kernel-schema — DO NOT EDIT.");
  lines.push("// Regenerate with `bun run generate`.");
  lines.push('import { describe, expect, test } from "bun:test";');
  lines.push('import { assertTransition, canTransition } from "../src/validate.ts";');
  lines.push("");

  let acceptCount = 0;
  let rejectCount = 0;

  for (const [typeName, table] of Object.entries(transitions)) {
    const states = Object.keys(table);
    lines.push(`describe("${typeName} transitions", () => {`);

    for (const from of states) {
      const legal = new Set(table[from as keyof typeof table] as readonly string[]);

      for (const to of legal) {
        acceptCount++;
        lines.push(`  test("accepts ${from} → ${to}", () => {`);
        lines.push(`    expect(canTransition("${typeName}", "${from}", "${to}")).toBe(true);`);
        lines.push(
          `    expect(() => assertTransition("${typeName}", "${from}", "${to}")).not.toThrow();`,
        );
        lines.push("  });");
      }

      for (const to of states) {
        if (legal.has(to)) continue;
        rejectCount++;
        lines.push(`  test("rejects ${from} → ${to}", () => {`);
        lines.push(`    expect(canTransition("${typeName}", "${from}", "${to}")).toBe(false);`);
        lines.push(
          `    expect(() => assertTransition("${typeName}", "${from}", "${to}")).toThrow(/${typeName}.*${from}.*${to}/);`,
        );
        lines.push("  });");
      }
    }

    lines.push("});");
    lines.push("");
  }

  lines.push(`// meta: accept=${acceptCount} reject=${rejectCount} total=${acceptCount + rejectCount}`);
  lines.push("");

  return lines.join("\n");
}

/** Counts used by reports and unit checks. */
export function countConformanceTests(): { accept: number; reject: number; total: number } {
  let accept = 0;
  let reject = 0;
  for (const table of Object.values(transitions)) {
    const states = Object.keys(table);
    for (const from of states) {
      const legal = table[from as keyof typeof table] as readonly string[];
      accept += legal.length;
      reject += states.length - legal.length;
    }
  }
  return { accept, reject, total: accept + reject };
}
