import type { ZodType } from "zod";
import { propertyDescription, type Schema } from "../define.ts";

function propertyLines(shape: Record<string, unknown>): string[] {
  const lines: string[] = [];
  for (const [name, field] of Object.entries(shape)) {
    const description = propertyDescription(field as ZodType) ?? "";
    lines.push(`- \`${name}\` — ${description}`);
  }
  return lines;
}

/**
 * Pure generator: schema in → ONTOLOGY.md string out.
 * Deterministic; does not touch the filesystem.
 */
export function generateDocs(schema: Schema): string {
  const lines: string[] = [];
  lines.push("# ONTOLOGY");
  lines.push("");
  lines.push("> Generated by `qf-kernel-schema`. Do not edit — regenerate with `bun run generate`.");
  lines.push("");

  lines.push("## Objects");
  lines.push("");
  for (const object of schema.objects) {
    lines.push(`### \`${object.name}\``);
    lines.push("");
    lines.push(object.description);
    lines.push("");
    lines.push(`- **lifecycle:** \`${object.lifecycle}\``);
    lines.push("- **properties:**");
    lines.push(...propertyLines(object.properties.shape));
    lines.push("");
  }

  lines.push("## Links");
  lines.push("");
  for (const link of schema.links) {
    lines.push(`### \`${link.name}\``);
    lines.push("");
    lines.push(link.description);
    lines.push("");
    lines.push(`- **lifecycle:** \`${link.lifecycle}\``);
    lines.push(`- **from:** \`${link.from}\``);
    lines.push(`- **to:** \`${link.to}\``);
    lines.push("");
  }

  lines.push("## Actions");
  lines.push("");
  for (const action of schema.actions) {
    lines.push(`### \`${action.name}\``);
    lines.push("");
    lines.push(action.description);
    lines.push("");
    lines.push(`- **lifecycle:** \`${action.lifecycle}\``);
    lines.push("- **input:**");
    lines.push(...propertyLines(action.input.shape));
    lines.push("");
  }

  return `${lines.join("\n")}`;
}
