// GENERATED by qf-kernel-schema — DO NOT EDIT.
// Regenerate with `bun run generate`.
import { describe, expect, test } from "bun:test";
import { assertTransition, canTransition } from "../src/validate.ts";

describe("run transitions", () => {
  test("accepts queued → running", () => {
    expect(canTransition("run", "queued", "running")).toBe(true);
    expect(() => assertTransition("run", "queued", "running")).not.toThrow();
  });
  test("rejects queued → queued", () => {
    expect(canTransition("run", "queued", "queued")).toBe(false);
    expect(() => assertTransition("run", "queued", "queued")).toThrow(/run.*queued.*queued/);
  });
  test("rejects queued → succeeded", () => {
    expect(canTransition("run", "queued", "succeeded")).toBe(false);
    expect(() => assertTransition("run", "queued", "succeeded")).toThrow(/run.*queued.*succeeded/);
  });
  test("rejects queued → failed", () => {
    expect(canTransition("run", "queued", "failed")).toBe(false);
    expect(() => assertTransition("run", "queued", "failed")).toThrow(/run.*queued.*failed/);
  });
  test("rejects queued → cancelled", () => {
    expect(canTransition("run", "queued", "cancelled")).toBe(false);
    expect(() => assertTransition("run", "queued", "cancelled")).toThrow(/run.*queued.*cancelled/);
  });
  test("accepts running → succeeded", () => {
    expect(canTransition("run", "running", "succeeded")).toBe(true);
    expect(() => assertTransition("run", "running", "succeeded")).not.toThrow();
  });
  test("accepts running → failed", () => {
    expect(canTransition("run", "running", "failed")).toBe(true);
    expect(() => assertTransition("run", "running", "failed")).not.toThrow();
  });
  test("accepts running → cancelled", () => {
    expect(canTransition("run", "running", "cancelled")).toBe(true);
    expect(() => assertTransition("run", "running", "cancelled")).not.toThrow();
  });
  test("rejects running → queued", () => {
    expect(canTransition("run", "running", "queued")).toBe(false);
    expect(() => assertTransition("run", "running", "queued")).toThrow(/run.*running.*queued/);
  });
  test("rejects running → running", () => {
    expect(canTransition("run", "running", "running")).toBe(false);
    expect(() => assertTransition("run", "running", "running")).toThrow(/run.*running.*running/);
  });
  test("rejects succeeded → queued", () => {
    expect(canTransition("run", "succeeded", "queued")).toBe(false);
    expect(() => assertTransition("run", "succeeded", "queued")).toThrow(/run.*succeeded.*queued/);
  });
  test("rejects succeeded → running", () => {
    expect(canTransition("run", "succeeded", "running")).toBe(false);
    expect(() => assertTransition("run", "succeeded", "running")).toThrow(/run.*succeeded.*running/);
  });
  test("rejects succeeded → succeeded", () => {
    expect(canTransition("run", "succeeded", "succeeded")).toBe(false);
    expect(() => assertTransition("run", "succeeded", "succeeded")).toThrow(/run.*succeeded.*succeeded/);
  });
  test("rejects succeeded → failed", () => {
    expect(canTransition("run", "succeeded", "failed")).toBe(false);
    expect(() => assertTransition("run", "succeeded", "failed")).toThrow(/run.*succeeded.*failed/);
  });
  test("rejects succeeded → cancelled", () => {
    expect(canTransition("run", "succeeded", "cancelled")).toBe(false);
    expect(() => assertTransition("run", "succeeded", "cancelled")).toThrow(/run.*succeeded.*cancelled/);
  });
  test("rejects failed → queued", () => {
    expect(canTransition("run", "failed", "queued")).toBe(false);
    expect(() => assertTransition("run", "failed", "queued")).toThrow(/run.*failed.*queued/);
  });
  test("rejects failed → running", () => {
    expect(canTransition("run", "failed", "running")).toBe(false);
    expect(() => assertTransition("run", "failed", "running")).toThrow(/run.*failed.*running/);
  });
  test("rejects failed → succeeded", () => {
    expect(canTransition("run", "failed", "succeeded")).toBe(false);
    expect(() => assertTransition("run", "failed", "succeeded")).toThrow(/run.*failed.*succeeded/);
  });
  test("rejects failed → failed", () => {
    expect(canTransition("run", "failed", "failed")).toBe(false);
    expect(() => assertTransition("run", "failed", "failed")).toThrow(/run.*failed.*failed/);
  });
  test("rejects failed → cancelled", () => {
    expect(canTransition("run", "failed", "cancelled")).toBe(false);
    expect(() => assertTransition("run", "failed", "cancelled")).toThrow(/run.*failed.*cancelled/);
  });
  test("rejects cancelled → queued", () => {
    expect(canTransition("run", "cancelled", "queued")).toBe(false);
    expect(() => assertTransition("run", "cancelled", "queued")).toThrow(/run.*cancelled.*queued/);
  });
  test("rejects cancelled → running", () => {
    expect(canTransition("run", "cancelled", "running")).toBe(false);
    expect(() => assertTransition("run", "cancelled", "running")).toThrow(/run.*cancelled.*running/);
  });
  test("rejects cancelled → succeeded", () => {
    expect(canTransition("run", "cancelled", "succeeded")).toBe(false);
    expect(() => assertTransition("run", "cancelled", "succeeded")).toThrow(/run.*cancelled.*succeeded/);
  });
  test("rejects cancelled → failed", () => {
    expect(canTransition("run", "cancelled", "failed")).toBe(false);
    expect(() => assertTransition("run", "cancelled", "failed")).toThrow(/run.*cancelled.*failed/);
  });
  test("rejects cancelled → cancelled", () => {
    expect(canTransition("run", "cancelled", "cancelled")).toBe(false);
    expect(() => assertTransition("run", "cancelled", "cancelled")).toThrow(/run.*cancelled.*cancelled/);
  });
});

describe("hypothesis transitions", () => {
  test("accepts open → supported", () => {
    expect(canTransition("hypothesis", "open", "supported")).toBe(true);
    expect(() => assertTransition("hypothesis", "open", "supported")).not.toThrow();
  });
  test("accepts open → rejected", () => {
    expect(canTransition("hypothesis", "open", "rejected")).toBe(true);
    expect(() => assertTransition("hypothesis", "open", "rejected")).not.toThrow();
  });
  test("accepts open → inconclusive", () => {
    expect(canTransition("hypothesis", "open", "inconclusive")).toBe(true);
    expect(() => assertTransition("hypothesis", "open", "inconclusive")).not.toThrow();
  });
  test("rejects open → open", () => {
    expect(canTransition("hypothesis", "open", "open")).toBe(false);
    expect(() => assertTransition("hypothesis", "open", "open")).toThrow(/hypothesis.*open.*open/);
  });
  test("rejects supported → open", () => {
    expect(canTransition("hypothesis", "supported", "open")).toBe(false);
    expect(() => assertTransition("hypothesis", "supported", "open")).toThrow(/hypothesis.*supported.*open/);
  });
  test("rejects supported → supported", () => {
    expect(canTransition("hypothesis", "supported", "supported")).toBe(false);
    expect(() => assertTransition("hypothesis", "supported", "supported")).toThrow(/hypothesis.*supported.*supported/);
  });
  test("rejects supported → rejected", () => {
    expect(canTransition("hypothesis", "supported", "rejected")).toBe(false);
    expect(() => assertTransition("hypothesis", "supported", "rejected")).toThrow(/hypothesis.*supported.*rejected/);
  });
  test("rejects supported → inconclusive", () => {
    expect(canTransition("hypothesis", "supported", "inconclusive")).toBe(false);
    expect(() => assertTransition("hypothesis", "supported", "inconclusive")).toThrow(/hypothesis.*supported.*inconclusive/);
  });
  test("rejects rejected → open", () => {
    expect(canTransition("hypothesis", "rejected", "open")).toBe(false);
    expect(() => assertTransition("hypothesis", "rejected", "open")).toThrow(/hypothesis.*rejected.*open/);
  });
  test("rejects rejected → supported", () => {
    expect(canTransition("hypothesis", "rejected", "supported")).toBe(false);
    expect(() => assertTransition("hypothesis", "rejected", "supported")).toThrow(/hypothesis.*rejected.*supported/);
  });
  test("rejects rejected → rejected", () => {
    expect(canTransition("hypothesis", "rejected", "rejected")).toBe(false);
    expect(() => assertTransition("hypothesis", "rejected", "rejected")).toThrow(/hypothesis.*rejected.*rejected/);
  });
  test("rejects rejected → inconclusive", () => {
    expect(canTransition("hypothesis", "rejected", "inconclusive")).toBe(false);
    expect(() => assertTransition("hypothesis", "rejected", "inconclusive")).toThrow(/hypothesis.*rejected.*inconclusive/);
  });
  test("rejects inconclusive → open", () => {
    expect(canTransition("hypothesis", "inconclusive", "open")).toBe(false);
    expect(() => assertTransition("hypothesis", "inconclusive", "open")).toThrow(/hypothesis.*inconclusive.*open/);
  });
  test("rejects inconclusive → supported", () => {
    expect(canTransition("hypothesis", "inconclusive", "supported")).toBe(false);
    expect(() => assertTransition("hypothesis", "inconclusive", "supported")).toThrow(/hypothesis.*inconclusive.*supported/);
  });
  test("rejects inconclusive → rejected", () => {
    expect(canTransition("hypothesis", "inconclusive", "rejected")).toBe(false);
    expect(() => assertTransition("hypothesis", "inconclusive", "rejected")).toThrow(/hypothesis.*inconclusive.*rejected/);
  });
  test("rejects inconclusive → inconclusive", () => {
    expect(canTransition("hypothesis", "inconclusive", "inconclusive")).toBe(false);
    expect(() => assertTransition("hypothesis", "inconclusive", "inconclusive")).toThrow(/hypothesis.*inconclusive.*inconclusive/);
  });
});

describe("ticket transitions", () => {
  test("accepts pending → win", () => {
    expect(canTransition("ticket", "pending", "win")).toBe(true);
    expect(() => assertTransition("ticket", "pending", "win")).not.toThrow();
  });
  test("accepts pending → loss", () => {
    expect(canTransition("ticket", "pending", "loss")).toBe(true);
    expect(() => assertTransition("ticket", "pending", "loss")).not.toThrow();
  });
  test("accepts pending → push", () => {
    expect(canTransition("ticket", "pending", "push")).toBe(true);
    expect(() => assertTransition("ticket", "pending", "push")).not.toThrow();
  });
  test("accepts pending → void", () => {
    expect(canTransition("ticket", "pending", "void")).toBe(true);
    expect(() => assertTransition("ticket", "pending", "void")).not.toThrow();
  });
  test("rejects pending → pending", () => {
    expect(canTransition("ticket", "pending", "pending")).toBe(false);
    expect(() => assertTransition("ticket", "pending", "pending")).toThrow(/ticket.*pending.*pending/);
  });
  test("rejects win → pending", () => {
    expect(canTransition("ticket", "win", "pending")).toBe(false);
    expect(() => assertTransition("ticket", "win", "pending")).toThrow(/ticket.*win.*pending/);
  });
  test("rejects win → win", () => {
    expect(canTransition("ticket", "win", "win")).toBe(false);
    expect(() => assertTransition("ticket", "win", "win")).toThrow(/ticket.*win.*win/);
  });
  test("rejects win → loss", () => {
    expect(canTransition("ticket", "win", "loss")).toBe(false);
    expect(() => assertTransition("ticket", "win", "loss")).toThrow(/ticket.*win.*loss/);
  });
  test("rejects win → push", () => {
    expect(canTransition("ticket", "win", "push")).toBe(false);
    expect(() => assertTransition("ticket", "win", "push")).toThrow(/ticket.*win.*push/);
  });
  test("rejects win → void", () => {
    expect(canTransition("ticket", "win", "void")).toBe(false);
    expect(() => assertTransition("ticket", "win", "void")).toThrow(/ticket.*win.*void/);
  });
  test("rejects loss → pending", () => {
    expect(canTransition("ticket", "loss", "pending")).toBe(false);
    expect(() => assertTransition("ticket", "loss", "pending")).toThrow(/ticket.*loss.*pending/);
  });
  test("rejects loss → win", () => {
    expect(canTransition("ticket", "loss", "win")).toBe(false);
    expect(() => assertTransition("ticket", "loss", "win")).toThrow(/ticket.*loss.*win/);
  });
  test("rejects loss → loss", () => {
    expect(canTransition("ticket", "loss", "loss")).toBe(false);
    expect(() => assertTransition("ticket", "loss", "loss")).toThrow(/ticket.*loss.*loss/);
  });
  test("rejects loss → push", () => {
    expect(canTransition("ticket", "loss", "push")).toBe(false);
    expect(() => assertTransition("ticket", "loss", "push")).toThrow(/ticket.*loss.*push/);
  });
  test("rejects loss → void", () => {
    expect(canTransition("ticket", "loss", "void")).toBe(false);
    expect(() => assertTransition("ticket", "loss", "void")).toThrow(/ticket.*loss.*void/);
  });
  test("rejects push → pending", () => {
    expect(canTransition("ticket", "push", "pending")).toBe(false);
    expect(() => assertTransition("ticket", "push", "pending")).toThrow(/ticket.*push.*pending/);
  });
  test("rejects push → win", () => {
    expect(canTransition("ticket", "push", "win")).toBe(false);
    expect(() => assertTransition("ticket", "push", "win")).toThrow(/ticket.*push.*win/);
  });
  test("rejects push → loss", () => {
    expect(canTransition("ticket", "push", "loss")).toBe(false);
    expect(() => assertTransition("ticket", "push", "loss")).toThrow(/ticket.*push.*loss/);
  });
  test("rejects push → push", () => {
    expect(canTransition("ticket", "push", "push")).toBe(false);
    expect(() => assertTransition("ticket", "push", "push")).toThrow(/ticket.*push.*push/);
  });
  test("rejects push → void", () => {
    expect(canTransition("ticket", "push", "void")).toBe(false);
    expect(() => assertTransition("ticket", "push", "void")).toThrow(/ticket.*push.*void/);
  });
  test("rejects void → pending", () => {
    expect(canTransition("ticket", "void", "pending")).toBe(false);
    expect(() => assertTransition("ticket", "void", "pending")).toThrow(/ticket.*void.*pending/);
  });
  test("rejects void → win", () => {
    expect(canTransition("ticket", "void", "win")).toBe(false);
    expect(() => assertTransition("ticket", "void", "win")).toThrow(/ticket.*void.*win/);
  });
  test("rejects void → loss", () => {
    expect(canTransition("ticket", "void", "loss")).toBe(false);
    expect(() => assertTransition("ticket", "void", "loss")).toThrow(/ticket.*void.*loss/);
  });
  test("rejects void → push", () => {
    expect(canTransition("ticket", "void", "push")).toBe(false);
    expect(() => assertTransition("ticket", "void", "push")).toThrow(/ticket.*void.*push/);
  });
  test("rejects void → void", () => {
    expect(canTransition("ticket", "void", "void")).toBe(false);
    expect(() => assertTransition("ticket", "void", "void")).toThrow(/ticket.*void.*void/);
  });
});

describe("event transitions", () => {
  test("accepts scheduled → live", () => {
    expect(canTransition("event", "scheduled", "live")).toBe(true);
    expect(() => assertTransition("event", "scheduled", "live")).not.toThrow();
  });
  test("accepts scheduled → void", () => {
    expect(canTransition("event", "scheduled", "void")).toBe(true);
    expect(() => assertTransition("event", "scheduled", "void")).not.toThrow();
  });
  test("rejects scheduled → scheduled", () => {
    expect(canTransition("event", "scheduled", "scheduled")).toBe(false);
    expect(() => assertTransition("event", "scheduled", "scheduled")).toThrow(/event.*scheduled.*scheduled/);
  });
  test("rejects scheduled → settled", () => {
    expect(canTransition("event", "scheduled", "settled")).toBe(false);
    expect(() => assertTransition("event", "scheduled", "settled")).toThrow(/event.*scheduled.*settled/);
  });
  test("accepts live → settled", () => {
    expect(canTransition("event", "live", "settled")).toBe(true);
    expect(() => assertTransition("event", "live", "settled")).not.toThrow();
  });
  test("rejects live → scheduled", () => {
    expect(canTransition("event", "live", "scheduled")).toBe(false);
    expect(() => assertTransition("event", "live", "scheduled")).toThrow(/event.*live.*scheduled/);
  });
  test("rejects live → live", () => {
    expect(canTransition("event", "live", "live")).toBe(false);
    expect(() => assertTransition("event", "live", "live")).toThrow(/event.*live.*live/);
  });
  test("rejects live → void", () => {
    expect(canTransition("event", "live", "void")).toBe(false);
    expect(() => assertTransition("event", "live", "void")).toThrow(/event.*live.*void/);
  });
  test("rejects settled → scheduled", () => {
    expect(canTransition("event", "settled", "scheduled")).toBe(false);
    expect(() => assertTransition("event", "settled", "scheduled")).toThrow(/event.*settled.*scheduled/);
  });
  test("rejects settled → live", () => {
    expect(canTransition("event", "settled", "live")).toBe(false);
    expect(() => assertTransition("event", "settled", "live")).toThrow(/event.*settled.*live/);
  });
  test("rejects settled → settled", () => {
    expect(canTransition("event", "settled", "settled")).toBe(false);
    expect(() => assertTransition("event", "settled", "settled")).toThrow(/event.*settled.*settled/);
  });
  test("rejects settled → void", () => {
    expect(canTransition("event", "settled", "void")).toBe(false);
    expect(() => assertTransition("event", "settled", "void")).toThrow(/event.*settled.*void/);
  });
  test("rejects void → scheduled", () => {
    expect(canTransition("event", "void", "scheduled")).toBe(false);
    expect(() => assertTransition("event", "void", "scheduled")).toThrow(/event.*void.*scheduled/);
  });
  test("rejects void → live", () => {
    expect(canTransition("event", "void", "live")).toBe(false);
    expect(() => assertTransition("event", "void", "live")).toThrow(/event.*void.*live/);
  });
  test("rejects void → settled", () => {
    expect(canTransition("event", "void", "settled")).toBe(false);
    expect(() => assertTransition("event", "void", "settled")).toThrow(/event.*void.*settled/);
  });
  test("rejects void → void", () => {
    expect(canTransition("event", "void", "void")).toBe(false);
    expect(() => assertTransition("event", "void", "void")).toThrow(/event.*void.*void/);
  });
});

describe("agent_session transitions", () => {
  test("accepts starting → running", () => {
    expect(canTransition("agent_session", "starting", "running")).toBe(true);
    expect(() => assertTransition("agent_session", "starting", "running")).not.toThrow();
  });
  test("rejects starting → starting", () => {
    expect(canTransition("agent_session", "starting", "starting")).toBe(false);
    expect(() => assertTransition("agent_session", "starting", "starting")).toThrow(/agent_session.*starting.*starting/);
  });
  test("rejects starting → blocked", () => {
    expect(canTransition("agent_session", "starting", "blocked")).toBe(false);
    expect(() => assertTransition("agent_session", "starting", "blocked")).toThrow(/agent_session.*starting.*blocked/);
  });
  test("rejects starting → cancelled", () => {
    expect(canTransition("agent_session", "starting", "cancelled")).toBe(false);
    expect(() => assertTransition("agent_session", "starting", "cancelled")).toThrow(/agent_session.*starting.*cancelled/);
  });
  test("rejects starting → failed", () => {
    expect(canTransition("agent_session", "starting", "failed")).toBe(false);
    expect(() => assertTransition("agent_session", "starting", "failed")).toThrow(/agent_session.*starting.*failed/);
  });
  test("rejects starting → closed", () => {
    expect(canTransition("agent_session", "starting", "closed")).toBe(false);
    expect(() => assertTransition("agent_session", "starting", "closed")).toThrow(/agent_session.*starting.*closed/);
  });
  test("accepts running → blocked", () => {
    expect(canTransition("agent_session", "running", "blocked")).toBe(true);
    expect(() => assertTransition("agent_session", "running", "blocked")).not.toThrow();
  });
  test("accepts running → cancelled", () => {
    expect(canTransition("agent_session", "running", "cancelled")).toBe(true);
    expect(() => assertTransition("agent_session", "running", "cancelled")).not.toThrow();
  });
  test("accepts running → failed", () => {
    expect(canTransition("agent_session", "running", "failed")).toBe(true);
    expect(() => assertTransition("agent_session", "running", "failed")).not.toThrow();
  });
  test("accepts running → closed", () => {
    expect(canTransition("agent_session", "running", "closed")).toBe(true);
    expect(() => assertTransition("agent_session", "running", "closed")).not.toThrow();
  });
  test("rejects running → starting", () => {
    expect(canTransition("agent_session", "running", "starting")).toBe(false);
    expect(() => assertTransition("agent_session", "running", "starting")).toThrow(/agent_session.*running.*starting/);
  });
  test("rejects running → running", () => {
    expect(canTransition("agent_session", "running", "running")).toBe(false);
    expect(() => assertTransition("agent_session", "running", "running")).toThrow(/agent_session.*running.*running/);
  });
  test("accepts blocked → running", () => {
    expect(canTransition("agent_session", "blocked", "running")).toBe(true);
    expect(() => assertTransition("agent_session", "blocked", "running")).not.toThrow();
  });
  test("accepts blocked → cancelled", () => {
    expect(canTransition("agent_session", "blocked", "cancelled")).toBe(true);
    expect(() => assertTransition("agent_session", "blocked", "cancelled")).not.toThrow();
  });
  test("accepts blocked → failed", () => {
    expect(canTransition("agent_session", "blocked", "failed")).toBe(true);
    expect(() => assertTransition("agent_session", "blocked", "failed")).not.toThrow();
  });
  test("rejects blocked → starting", () => {
    expect(canTransition("agent_session", "blocked", "starting")).toBe(false);
    expect(() => assertTransition("agent_session", "blocked", "starting")).toThrow(/agent_session.*blocked.*starting/);
  });
  test("rejects blocked → blocked", () => {
    expect(canTransition("agent_session", "blocked", "blocked")).toBe(false);
    expect(() => assertTransition("agent_session", "blocked", "blocked")).toThrow(/agent_session.*blocked.*blocked/);
  });
  test("rejects blocked → closed", () => {
    expect(canTransition("agent_session", "blocked", "closed")).toBe(false);
    expect(() => assertTransition("agent_session", "blocked", "closed")).toThrow(/agent_session.*blocked.*closed/);
  });
  test("accepts cancelled → closed", () => {
    expect(canTransition("agent_session", "cancelled", "closed")).toBe(true);
    expect(() => assertTransition("agent_session", "cancelled", "closed")).not.toThrow();
  });
  test("rejects cancelled → starting", () => {
    expect(canTransition("agent_session", "cancelled", "starting")).toBe(false);
    expect(() => assertTransition("agent_session", "cancelled", "starting")).toThrow(/agent_session.*cancelled.*starting/);
  });
  test("rejects cancelled → running", () => {
    expect(canTransition("agent_session", "cancelled", "running")).toBe(false);
    expect(() => assertTransition("agent_session", "cancelled", "running")).toThrow(/agent_session.*cancelled.*running/);
  });
  test("rejects cancelled → blocked", () => {
    expect(canTransition("agent_session", "cancelled", "blocked")).toBe(false);
    expect(() => assertTransition("agent_session", "cancelled", "blocked")).toThrow(/agent_session.*cancelled.*blocked/);
  });
  test("rejects cancelled → cancelled", () => {
    expect(canTransition("agent_session", "cancelled", "cancelled")).toBe(false);
    expect(() => assertTransition("agent_session", "cancelled", "cancelled")).toThrow(/agent_session.*cancelled.*cancelled/);
  });
  test("rejects cancelled → failed", () => {
    expect(canTransition("agent_session", "cancelled", "failed")).toBe(false);
    expect(() => assertTransition("agent_session", "cancelled", "failed")).toThrow(/agent_session.*cancelled.*failed/);
  });
  test("accepts failed → closed", () => {
    expect(canTransition("agent_session", "failed", "closed")).toBe(true);
    expect(() => assertTransition("agent_session", "failed", "closed")).not.toThrow();
  });
  test("rejects failed → starting", () => {
    expect(canTransition("agent_session", "failed", "starting")).toBe(false);
    expect(() => assertTransition("agent_session", "failed", "starting")).toThrow(/agent_session.*failed.*starting/);
  });
  test("rejects failed → running", () => {
    expect(canTransition("agent_session", "failed", "running")).toBe(false);
    expect(() => assertTransition("agent_session", "failed", "running")).toThrow(/agent_session.*failed.*running/);
  });
  test("rejects failed → blocked", () => {
    expect(canTransition("agent_session", "failed", "blocked")).toBe(false);
    expect(() => assertTransition("agent_session", "failed", "blocked")).toThrow(/agent_session.*failed.*blocked/);
  });
  test("rejects failed → cancelled", () => {
    expect(canTransition("agent_session", "failed", "cancelled")).toBe(false);
    expect(() => assertTransition("agent_session", "failed", "cancelled")).toThrow(/agent_session.*failed.*cancelled/);
  });
  test("rejects failed → failed", () => {
    expect(canTransition("agent_session", "failed", "failed")).toBe(false);
    expect(() => assertTransition("agent_session", "failed", "failed")).toThrow(/agent_session.*failed.*failed/);
  });
  test("rejects closed → starting", () => {
    expect(canTransition("agent_session", "closed", "starting")).toBe(false);
    expect(() => assertTransition("agent_session", "closed", "starting")).toThrow(/agent_session.*closed.*starting/);
  });
  test("rejects closed → running", () => {
    expect(canTransition("agent_session", "closed", "running")).toBe(false);
    expect(() => assertTransition("agent_session", "closed", "running")).toThrow(/agent_session.*closed.*running/);
  });
  test("rejects closed → blocked", () => {
    expect(canTransition("agent_session", "closed", "blocked")).toBe(false);
    expect(() => assertTransition("agent_session", "closed", "blocked")).toThrow(/agent_session.*closed.*blocked/);
  });
  test("rejects closed → cancelled", () => {
    expect(canTransition("agent_session", "closed", "cancelled")).toBe(false);
    expect(() => assertTransition("agent_session", "closed", "cancelled")).toThrow(/agent_session.*closed.*cancelled/);
  });
  test("rejects closed → failed", () => {
    expect(canTransition("agent_session", "closed", "failed")).toBe(false);
    expect(() => assertTransition("agent_session", "closed", "failed")).toThrow(/agent_session.*closed.*failed/);
  });
  test("rejects closed → closed", () => {
    expect(canTransition("agent_session", "closed", "closed")).toBe(false);
    expect(() => assertTransition("agent_session", "closed", "closed")).toThrow(/agent_session.*closed.*closed/);
  });
});

// meta: accept=24 reject=94 total=118
